import {
  Laptop,
  Server,
  Network,
  Cloud,
  Monitor,
  Globe,
  ClipboardCheck,
  PackageOpen,
  Cable,
  HardDrive,
  Shield,
  Cpu,
} from "lucide-react";

export interface SheetConfig {
  slug: string;
  name: string;
  prismaModel: string;
  icon: React.ElementType;
  headers: string[];
  fields: string[];
}

export const sheetConfigs: SheetConfig[] = [
  {
    slug: "laptop-record",
    name: "Laptop Record",
    prismaModel: "laptopRecord",
    icon: Laptop,
    headers: [
      "sr",
      "Employee Name",
      "Department",
      "Status",
      "Date",
      "Serial Number",
      "LAPTOP",
      "MODEL",
      "CPU",
      "RAM",
      "HDD",
      "LCD",
      "Keyboard",
      "MOUSE",
      "Laptop Bag",
      "HeadPhones",
      "Mousepad",
      "Comment",
    ],
    fields: [
      "sr",
      "employeeName",
      "department",
      "status",
      "date",
      "serialNumber",
      "laptop",
      "model",
      "cpu",
      "ram",
      "hdd",
      "lcd",
      "keyboard",
      "mouse",
      "laptopBag",
      "headPhones",
      "mousepad",
      "comment",
    ],
  },
  {
    slug: "servers-devices",
    name: "Lab Servers",
    prismaModel: "serverDevice",
    icon: Server,
    headers: [
      "MODEL",
      "Serial Number",
      "CPUs",
      "PROCESSOR",
      "RAM",
      "STORAGE",
      "I.P",
      "OS version",
      "STATUS",
      "No of Existing VMs",
      "ILO IPs",
    ],
    fields: [
      "model",
      "serialNumber",
      "cpus",
      "processor",
      "ram",
      "storage",
      "ip",
      "osVersion",
      "status",
      "noOfExistingVms",
      "iloIps",
    ],
  },
  {
    slug: "iloidrac",
    name: "iloidrac",
    prismaModel: "iloIdrac",
    icon: Network,
    headers: ["Servers", "IP", "ilo/idrac IP", "Switch port", "Comments"],
    fields: ["servers", "ip", "iloIdracIp", "switchPort", "comments"],
  },
  {
    slug: "cloud-vm-list",
    name: "Cloud VM List",
    prismaModel: "cloudVm",
    icon: Cloud,
    headers: [
      "Sr",
      "Cloud VM - usage - description",
      "IP Address",
      "FQDN ( if any)",
      "Cloud",
      "Specifications",
      "User / Department",
      "SSL Status",
      "SSL Expiry",
    ],
    fields: [
      "no",
      "cloudVmUsageDescription",
      "ipAddress",
      "fqdn",
      "cloud",
      "specifications",
      "userDepartment",
      "sslStatus",
      "sslExpiry",
    ],
  },
  {
    slug: "lab-vm-list",
    name: "Lab VM List",
    prismaModel: "labVm",
    icon: Monitor,
    headers: [
      "sr",
      "VM Name",
      "Host Server",
      "Memory Size",
      "IP Address",
      "DNS Name",
      "SSL Status",
      "SSL Expiry",
      "Public IP / Middleware Proxy",
      "User / Team",
    ],
    fields: [
      "sr",
      "vmName",
      "hostServer",
      "memorySize",
      "ipAddress",
      "dnsName",
      "sslStatus",
      "sslExpiry",
      "publicIpMiddlewareProxy",
      "userTeam",
    ],
  },
  {
    slug: "public-fqdn",
    name: "public FQDN",
    prismaModel: "publicFqdn",
    icon: Globe,
    headers: [
      "form-etl.expertflow.com",
      "Public IP / Middleware",
      "Points to",
      "Usage / User",
      "MTT Host DO",
    ],
    fields: [
      "formEtlExpertflowCom",
      "publicIpMiddleware",
      "pointsTo",
      "usageUser",
      "mttHostDo",
    ],
  },
  {
    slug: "gatepass",
    name: "GatePass",
    prismaModel: "gatePass",
    icon: ClipboardCheck,
    headers: [
      "gp_id",
      "particulars",
      "serial_number",
      "quantity",
      "issued_by",
      "recieved_to",
      "time_out",
      "time_in",
      "remarks",
      "Charger",
    ],
    fields: [
      "gpId",
      "particulars",
      "serialNumber",
      "quantity",
      "issuedBy",
      "recievedTo",
      "timeOut",
      "timeIn",
      "remarks",
      "charger",
    ],
  },
  {
    slug: "received-items",
    name: "Received Items",
    prismaModel: "receivedItem",
    icon: PackageOpen,
    headers: [
      "Received From",
      "Particulars",
      "Quantity",
      "Received By",
      "Received Date",
      "Remarks",
    ],
    fields: [
      "receivedFrom",
      "particulars",
      "quantity",
      "receivedBy",
      "receivedDate",
      "remarks",
    ],
  },
  {
    slug: "ports-detail",
    name: "Ports-Detail",
    prismaModel: "portDetail",
    icon: Cable,
    headers: [
      "Sr no",
      "Device Name",
      "",
      "Switch-1 Cisco 2960",
      "Switch-2 Cisco 3750",
      "",
      "Sr no",
      "Device Name",
      "",
      "Switch-1 Cisco 2960",
      "Switch-2 Cisco 3750",
    ],
    fields: [
      "srNo",
      "deviceName",
      "col3",
      "switch1Cisco2960",
      "switch2Cisco3750",
      "col6",
      "srNo2",
      "deviceName2",
      "col9",
      "switch1Cisco2960_2",
      "switch2Cisco3750_2",
    ],
  },
  {
    slug: "free-vms",
    name: "Free VMs",
    prismaModel: "freeVm",
    icon: HardDrive,
    headers: [
      "VM Name",
      "Server IP",
      "RAM",
      "VM IP",
      "Domain Name",
      "FQDN",
      "Deleted on",
      "Department",
    ],
    fields: [
      "vmName",
      "serverIp",
      "ram",
      "vmIp",
      "domainName",
      "fqdn",
      "deletedOn",
      "department",
    ],
  },
  {
    slug: "devices",
    name: "Devices",
    prismaModel: "device",
    icon: Cpu,
    headers: ["Device", "MODEL", "Model Number", "Serial Number", "I.P", "Battery", "STATUS", "BW"],
    fields: ["device", "model", "modelNumber", "serialNumber", "ip", "battery", "status", "bw"],
  },
];

export const sheetConfigMap = new Map(sheetConfigs.map((s) => [s.slug, s]));

export function getSheetConfig(slug: string): SheetConfig | undefined {
  return sheetConfigMap.get(slug);
}
