import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('192.168.1.38', username='root', password='ExpertFlow123', timeout=5)
stdin, stdout, stderr = ssh.exec_command('docker ps --format "{{.Names}} {{.Status}}"')
print('Containers:')
print(stdout.read().decode())
stdin, stdout, stderr = ssh.exec_command('docker logs --tail 20 hungry_knuth 2>/dev/null || echo "no logs"')
print('Seed logs:')
print(stdout.read().decode()[:3000])
ssh.close()
